### PR TITLE
Support for pre-populating the form

### PR DESCRIPTION
**Pull request by stuporglue**
Hi Kodie, 

I needed to be able to pre-populate repeaters as I mentioned here: https://github.com/kodie/gravityforms-repeater/issues/4

This pull request fulfills that requirement at least well enough for my own needs, and hopefully for others too. It should support all of the fields that gravityforms-repeater supports. 
### How it works / changes
- The repeater itself gets support for prepopulate_field_setting
  - The prepopulate setting for fields inside the repeater is ignored
- The prepopulate value should be a JSON string which corresponds to the serialized array which is stored for the repeater. 
  - Set the prepopulate value like you would any other, eg. by setting $_GET in your template or plugin
- The hidden repeater input gains a new data-prepopulate attribute with the json string as the value
- In gfRepeater_start we attempt to use the JSON string to determine how many repeats to have, and populate them with the data
### Good Stuff
- Seems to work for all field types
- Seems to be round-trip safe
  - I tested by getting the serialized string from the database, unserialized it and json_encoded it and used that to pre-populate and re-submit the form. The resulting strings in the database are identical.
### Notes
- This is my first time mucking around with gravity forms plugins
- I haven't tested repeaters with initial/min/max settings, and instead assuming that if you were passing in data to pre-populate the repeater, you probably wanted that many repeats.
- I wasn't sure how you created your gf-repeater.min.js file so I didn't update that. 

See the attached form export for a test case. You should be able to import it, and then add the attached php code to a theme or plugin to easily test the functionality.
[prepopulate.txt](https://github.com/kodie/gravityforms-repeater/files/44636/prepopulate.txt)
[gravityforms-export-2015-11-26.json.txt](https://github.com/kodie/gravityforms-repeater/files/44639/gravityforms-export-2015-11-26.json.txt)

### CODE REVIEW

**Comment by stuporglue** [comment]
I found a caveat that I'm trying to fix now, it looks like this isn't working quite right on forms with pagination. It is still working on single-page forms.

**Comment by stuporglue** [comment]
I updated the pull request so it works on multi-page forms now.

**Comment by kodie** [comment]
Hey Michael! This is awesome! Saves me some work! haha. I haven't gotten a chance to test it out yet due to holidays and holiday shopping but I'll check it out more this weekend! I hope you don't mind if I make a few changes to your commits!

Thanks again Michael!

**Comment by stuporglue** [comment]
Yeah, feel free to change whatever you want or need.

**Comment by marcelderuiter** [comment]
@kodie, have you implemented this yet? 
I'd also like to use the "gravity_form" function to embed and populate my forms, but there seems to be no support for this. Am I missing something?

**Comment by marcelderuiter** [comment]
@kodie have you implemented this yet? 

I would like to use GFAPI::get_entry to populate the repeater field but without having to set every single repeater child individually. This feature would really make things easier.

**Comment by ahmadtawakol** [comment]
I'm having problems populating repeater fields. I'm able to populate regular fields without any problems, but I can't figure out how to do it for repeater fields.

How do I structure the parameter name for a repeater field? Which parameter names am I supposed to use? I have set the parameter name for the repeater block and I set the parameter names for the fields inside the block. I am doing this in PHP.

Any help would be much appreciated. I'm working on a big project and this step is the only thing preventing me from completing the whole project, and everything depends on this form.

**Pull request closed without merging**
